module.exports = Object.freeze({
  'castor-oil': { name: 'Organic Golden Castor Oil 100ml', unitAmount: 10900 },
  sustain: { name: 'Sustain Me', unitAmount: 21000 },
  'castor-oil-250ml': { name: 'Organic Golden Castor Oil 250ml', unitAmount: 16900 },
  'breast-castor-pack': { name: 'Breast Castor Oil Pack', unitAmount: 21900 },
  'back-abdomen-castor-pack': { name: 'Back Abdomen Castor Oil Pack', unitAmount: 24900 },
  'self-heal-by-design': { name: 'Self Heal By Design', unitAmount: 15000 },
  'tre-lune-wild-yam-cream': { name: 'Tre Lune Wild Yam Cream', unitAmount: 26000 },
  'ezyprotein-vegan-vanilla-protein-powder-superfood-blend-1kg': { name: 'Ezyprotein Vegan Vanilla Protein Powder & Superfood Blend 1kg', unitAmount: 36690 },
  'ezyprotein-vegan-wild-berry-protein-powder-superfood-blend-800g': { name: 'Ezyprotein Vegan Wild Berry Protein Powder & Superfood Blend 800g', unitAmount: 36690 },
  'ezyprotein-vegan-natural-protein-powder-superfood-blend-1kg': { name: 'Ezyprotein Vegan Natural Protein Powder & Superfood Blend 1kg', unitAmount: 36690 },
  'ezyprotein-vegan-chocolate-protein-powder-superfood-blend-1kg': { name: 'Ezyprotein Vegan Chocolate Protein Powder & Superfood Blend 1kg', unitAmount: 36690 },
  'snt-organic-turmeric-ground-40g': { name: 'SNT Organic Turmeric Ground 40g', unitAmount: 2000 },
  'snt-organic-cayenne-pepper-40g': { name: 'SNT Organic Cayenne Pepper 40g', unitAmount: 2400 },
  'snt-organic-dandelion-leaves-tea-bag-18s': { name: 'SNT Organic Dandelion Leaves Tea Bag 18s', unitAmount: 2800 },
  'snt-organic-camomile-leaves-tea-bag-18s': { name: 'SNT Organic Camomile Leaves Tea Bag 18s', unitAmount: 2800 },
  'garden-of-the-andes-organic-assorted-tea-20s': { name: 'Garden of The Andes Organic Assorted Tea 20s', unitAmount: 2590 },
  'garden-of-the-andes-organic-patagonian-berries-20s': { name: 'Garden of The Andes Organic Patagonian Berries 20s', unitAmount: 2890 },
  'garden-of-the-andes-organic-rosehips-with-hibiscus-20s': { name: 'Garden of The Andes Organic Rosehips with Hibiscus 20s', unitAmount: 2890 },
  'celtic-sea-salt-fine-200g': { name: 'Celtic Sea Salt Fine 200g', unitAmount: 1300 },
  'essential-oil-eucalyptus-10ml': { name: 'Essential Oil - Eucalyptus 10ml', unitAmount: 6000 },
  'essential-oil-frankincense-wild-5ml': { name: 'Essential Oil - Frankincense Wild 5ml', unitAmount: 13000 },
  'essential-oil-tea-tree-10ml': { name: 'Essential Oil - Tea Tree 10ml', unitAmount: 9500 },
  'organic-virgin-raw-coconut-oil-250ml': { name: 'Organic Virgin Raw Coconut Oil 250ml', unitAmount: 4500 },
  'organic-e-v-olive-oil-250ml': { name: 'Organic E/V Olive Oil 250ml', unitAmount: 4600 },
  'organic-avocado-oil-250ml': { name: 'Organic Avocado Oil 250ml', unitAmount: 8000 },
  'snt-organic-rose-flower-buds-30g': { name: 'SNT Organic Rose Flower Buds 30g', unitAmount: 4300 },
  'activated-charcoal-powder-275g': { name: 'Activated Charcoal Powder 275g', unitAmount: 15900 },
  'garden-of-the-andes-organic-peppermint-20s': { name: 'Garden of The Andes Organic Peppermint 20s', unitAmount: 1990 },
  'neck-castor-oil-pack': { name: 'Neck Castor Oil Pack', unitAmount: 17900 },
  'pelvic-castor-oil-pack': { name: 'Pelvic Castor Oil Pack', unitAmount: 24900 },
  'organic-golden-castor-oil-500ml': { name: 'Organic Golden Castor Oil 500ml', unitAmount: 26900 },
  'castor-oil-hair-wrap': { name: 'Castor Oil Hair Wrap', unitAmount: 21900 },
  'organic-golden-castor-oil-roll-on-with-rose-quartz': { name: 'Organic Golden Castor Oil Roll-on with Rose Quartz', unitAmount: 19900 },
  'cotton-flannel-insert-straps-for-castor-oil-pack': { name: 'Cotton Flannel Insert + Straps for Castor Oil Pack', unitAmount: 17900 },
  'beauty-sleep-castor-oil-eye-mask': { name: 'Beauty Sleep Castor Oil Eye Mask', unitAmount: 17900 },
  'liver-castor-oil-pack': { name: 'Liver Castor Oil Pack', unitAmount: 23900 },
  'kid-castor-oil-pack': { name: 'Kids Castor Oil Pack', unitAmount: 21900 }
});
